lqr_local_planner:
  lookhead_time: 1.0
  min_lookhead_distance: 0.3
  max_lookhead_distance: 0.9
  goal_dist_tol: 0.2
  rotate_tol: 0.5
  base_frame: "base_link"
  map_frame: "map"
  max_v: 0.8
  min_v: 0.2
  max_inc_v: 0.5
  max_w: 1.75
  min_w: 0.1
  max_w_inc: 1.75
  controller_frequancy: 20
  max_iter: 1000
  eps_iter: 0.1
  transform_tolerance: 0.1
  Q_matrix_diag: [1.0, 1.0, 1.0]
  R_matrix_diag: [0.1, 0.1]
